### ISSUE TITLE
RuntimeError: FIND was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by shreyanc** [hugofloresgarcia/vampnet#10]
Steps:
1. Create conda env
2. Install python=3.9
3. Install vampnet using `pip install -e ./vampnet`
4. `python scripts/exp/fine_tune.py /path/to/audio_dir <fine_tune_name>`
5. `python scripts/exp/train.py --args.load conf/generated/<fine_tune_name>/coarse.yml`

**GPU Information:**
- GPU Model: GeForce RTX 2080 Ti
- NVIDIA Driver Version: 450.236.01

**CUDA Version:**
- CUDA Toolkit Version: 11.0

**Comment by shreyanc** [comment]
@hugofloresgarcia  Any idea why this error is occurring? I tried reinstalling pytorch, and running on different gpus. I'm just using it out of the box, without any changes.

**Comment by hugofloresgarcia** [comment]
Hi! Could you provide a full stack trace? Wanna see if there's any other info that could be helpful

**Comment by shreyanc** [comment]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /share/home/shreyan/PROJECTS/vampnet/scripts/exp/train.py:673 in <module>               │
│                                                                                                  │
│   670 │   │   with Accelerator() as accel:                                                       │
│   671 │   │   │   if accel.local_rank != 0:                                                      │
│   672 │   │   │   │   sys.tracebacklimit = 0                                                     │
│ ❱ 673 │   │   │   train(args, accel)                                                             │
│   674                                                                                            │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/argbind/argbind.py:159 in   │
│ cmd_func                                                                                         │
│                                                                                                  │
│   156 │   │   │   │   else:                                                                      │
│   157 │   │   │   │   │   scope = None                                                           │
│   158 │   │   │   │   print(_format_func_debug(prefix, kwargs, scope))                           │
│ ❱ 159 │   │   │   return func(*cmd_args, **kwargs)                                               │
│   160 │   │                                                                                      │
│   161 │   │   if is_class:                                                                       │
│   162 │   │   │   setattr(object_or_func, "__init__", cmd_func)                                  │
│                                                                                                  │
│ /share/home/shreyan/PROJECTS/vampnet/scripts/exp/train.py:642 in train                  │
│                                                                                                  │
│   639 │                                                                                          │
│   640 │   with tracker.live:                                                                     │
│   641 │   │   for tracker.step, batch in enumerate(train_dataloader, start=tracker.step):        │
│ ❱ 642 │   │   │   train_loop(state, batch, accel)                                                │
│   643 │   │   │                                                                                  │
│   644 │   │   │   last_iter = (                                                                  │
│   645 │   │   │   │   tracker.step == num_iters - 1 if num_iters is not None else False          │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/audiotools/ml/decorators.py │
│ :375 in decorated                                                                                │
│                                                                                                  │
│   372 │   │   def decorator(fn):                                                                 │
│   373 │   │   │   @wraps(fn)                                                                     │
│   374 │   │   │   def decorated(*args, **kwargs):                                                │
│ ❱ 375 │   │   │   │   output = fn(*args, **kwargs)                                               │
│   376 │   │   │   │   if self.rank == 0:                                                         │
│   377 │   │   │   │   │   nonlocal value_type, label                                             │
│   378 │   │   │   │   │   metrics = self.metrics[label][value_type]                              │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/audiotools/ml/decorators.py │
│ :321 in decorated                                                                                │
│                                                                                                  │
│   318 │   │   def decorator(fn):                                                                 │
│   319 │   │   │   @wraps(fn)                                                                     │
│   320 │   │   │   def decorated(*args, **kwargs):                                                │
│ ❱ 321 │   │   │   │   output = fn(*args, **kwargs)                                               │
│   322 │   │   │   │   if not isinstance(output, dict):                                           │
│   323 │   │   │   │   │   self.update(label, fn.__name__)                                        │
│   324 │   │   │   │   │   return output                                                          │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/audiotools/ml/decorators.py │
│ :107 in decorated                                                                                │
│                                                                                                  │
│   104 │   │   @wraps(fn)                                                                         │
│   105 │   │   def decorated(*args, **kwargs):                                                    │
│   106 │   │   │   s = time.perf_counter()                                                        │
│ ❱ 107 │   │   │   output = fn(*args, **kwargs)                                                   │
│   108 │   │   │   assert isinstance(output, dict)                                                │
│   109 │   │   │   e = time.perf_counter()                                                        │
│   110 │   │   │   output[f"{prefix}/{fn.__name__}"] = e - s                                      │
│                                                                                                  │
│ /share/home/shreyan/PROJECTS/vampnet/scripts/exp/train.py:210 in train_loop             │
│                                                                                                  │
│   207 │   with accel.autocast():                                                                 │
│   208 │   │   with torch.inference_mode():                                                       │
│   209 │   │   │   state.codec.to(accel.device)                                                   │
│ ❱ 210 │   │   │   z = state.codec.encode(signal.samples, signal.sample_rate)["codes"]            │
│   211 │   │   │   z = z[:, : vn.n_codebooks, :]                                                  │
│   212 │   │                                                                                      │
│   213 │   │   n_batch = z.shape[0]                                                               │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/lac/model/lac.py:273 in     │
│ encode                                                                                           │
│                                                                                                  │
│   270 │   │   audio_data, length = self.preprocess(audio_data, sample_rate)                      │
│   271 │   │   out["length"] = length                                                             │
│   272 │   │                                                                                      │
│ ❱ 273 │   │   out["z"] = self.encoder(audio_data)                                                │
│   274 │   │   out.update(self.quantizer(out["z"], n_quantizers))                                 │
│   275 │   │   return out                                                                         │
│   276                                                                                            │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1501 in _call_impl                                                                               │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/lac/model/lac.py:87 in      │
│ forward                                                                                          │
│                                                                                                  │
│    84 │   │   self.enc_dim = d_model                                                             │
│    85 │                                                                                          │
│    86 │   def forward(self, x):                                                                  │
│ ❱  87 │   │   return self.block(x)                                                               │
│    88                                                                                            │
│    89                                                                                            │
│    90 class ResidualLayer(nn.Module):                                                            │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1501 in _call_impl                                                                               │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/torch/nn/modules/container. │
│ py:217 in forward                                                                                │
│                                                                                                  │
│   214 │   # with Any as TorchScript expects a more precise type                                  │
│   215 │   def forward(self, input):                                                              │
│   216 │   │   for module in self:                                                                │
│ ❱ 217 │   │   │   input = module(input)                                                          │
│   218 │   │   return input                                                                       │
│   219 │                                                                                          │
│   220 │   def append(self, module: Module) -> 'Sequential':                                      │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1538 in _call_impl                                                                               │
│                                                                                                  │
│   1535 │   │   │   bw_hook = hooks.BackwardHook(self, full_backward_hooks, backward_pre_hooks)   │
│   1536 │   │   │   args = bw_hook.setup_input_hook(args)                                         │
│   1537 │   │                                                                                     │
│ ❱ 1538 │   │   result = forward_call(*args, **kwargs)                                            │
│   1539 │   │   if _global_forward_hooks or self._forward_hooks:                                  │
│   1540 │   │   │   for hook_id, hook in (                                                        │
│   1541 │   │   │   │   *_global_forward_hooks.items(),                                           │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/torch/nn/modules/conv.py:31 │
│ 3 in forward                                                                                     │
│                                                                                                  │
│    310 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    311 │                                                                                         │
│    312 │   def forward(self, input: Tensor) -> Tensor:                                           │
│ ❱  313 │   │   return self._conv_forward(input, self.weight, self.bias)                          │
│    314                                                                                           │
│    315                                                                                           │
│    316 class Conv2d(_ConvNd):                                                                    │
│                                                                                                  │
│ /share/home/shreyan/miniconda3/envs/vamp/lib/python3.9/site-packages/torch/nn/modules/conv.py:30 │
│ 9 in _conv_forward                                                                               │
│                                                                                                  │
│    306 │   │   │   return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=sel  │
│    307 │   │   │   │   │   │   │   weight, bias, self.stride,                                    │
│    308 │   │   │   │   │   │   │   _single(0), self.dilation, self.groups)                       │
│ ❱  309 │   │   return F.conv1d(input, weight, bias, self.stride,                                 │
│    310 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    311 │                                                                                         │
│    312 │   def forward(self, input: Tensor) -> Tensor:                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: FIND was unable to find an engine to execute this computation

**Comment by shreyanc** [comment]
@hugofloresgarcia That's a rather long and ugly looking stacktrace. Here's a screenshot of the bottom part:

![image](https://github.com/hugofloresgarcia/vampnet/assets/22148499/a3cb78ff-ee67-48a7-b688-5b9b292324e0)

**Comment by shreyanc** [comment]
Was able to resolve it. The issue was probably a cuda/pytorch version mismatch. 

Used the solution from https://github.com/mymusise/ChatGLM-Tuning/issues/53#issuecomment-1488338535:

`pip3 install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116`
