### ISSUE TITLE
Two minor installation issues

### ISSUE THREAD

**Issue by orrp** [hugofloresgarcia/vampnet#14]
Tested first on Macbook with M1 Max, then switched to a `g4` instance on AWS EC2.

# Need `numpy 1.23`
Steps to reproduce:

1. Create fresh conda environment (I used `python=3.11`).
2. Install package as described in [Setting Up](https://github.com/hugofloresgarcia/vampnet#setting-up).
3. Run `python app.py --args.load conf/interface.yml --Interface.device cuda`

Expected: It runs.
Actual: I get an error `ImportError: numpy.core.multiarray failed to import` (full stack trace below).

[The internet](https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import) says that this is due to an old numpy version. I upgraded to ~~`1.25`~~ ~~`1.24`~~ `1.23` which resolved the problem, but note that `vampnet` wants `numpy==1.22`. Might be worth allowing a newer version?
*EDIT:* NumPy `1.25` [led to a problem with Numba](https://github.com/hugofloresgarcia/vampnet/issues/14#issuecomment-1678204494). Numpy `1.24` leads to [a problem with `madmom`](https://github.com/hugofloresgarcia/vampnet/issues/14#issuecomment-1678254949). So numpy version `1.23` is the only one that works.

```
python app.py --args.load conf/interface.yml --Interface.device cuda


/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/torchaudio/compliance/kaldi.py:22: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  EPSILON = torch.tensor(torch.finfo(torch.float).eps)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "/Users/orrp/code/research/vampnet/app.py", line 12, in <module>
    import gradio as gr
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/gradio/utils.py", line 36, in <module>
    import matplotlib
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/matplotlib/__init__.py", line 129, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/matplotlib/ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "/opt/anaconda3/envs/vampnet/lib/python3.11/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
```

# Missing packages
The next issue I encountered, after the above, was `ModuleNotFoundError: No module named 'torch_pitch_shift'`. Solved by `pip install torch_pitch_shift`.

After running the example file + default preset through the UI, `madmom` was missing. `pip install madmom` solved this one.

May want to add this to `torch_pitch_shift `and `madmom` to `setup.py`.

**Comment by orrp** [comment]
And a note: After downloading the models, in `python app.py --args.load conf/interface.yml --Interface.device cuda` I changed `cuda` to `mps` (because of the M1 architecture) and it launched out of the box! (Though I did encounter more issues, see next).

**EDIT:** Unsurprisingly, `MPS` cannot work because of an unsupported torch operation (`aten::_weight_norm_interface`). Will switch to CUDA. It was worth a shot :)

**Comment by orrp** [comment]
Regarding the first issue: I launched the UI, loaded the example file, used the default preset (strong periodic variation) and hit generate. Then I got `ImportError: Numba needs NumPy 1.24 or less`. Downgrading from 1.25 to 1.24 solved the problem.

**Comment by orrp** [comment]
Update: Both issues (`numpy` version, and missing `torch_pitch_shift`) occur when installing on Linux (some EC2 instance).

**Comment by orrp** [comment]
Jk, `madmom` will not work with `numpy` version `1.24` because it uses `np.float` ([related StackOverflow](https://stackoverflow.com/questions/74844262/how-can-i-solve-error-module-numpy-has-no-attribute-float-in-python)). But `1.23` works.

**Comment by hugofloresgarcia** [comment]
thanks so much for getting this Orr!
