### ISSUE TITLE
Remove support for Python>3.9

### ISSUE THREAD

**Issue by orrp** [hugofloresgarcia/vampnet#15]
Currently, the readme states that setup requires Python 3.9 or later. But Python 3.10 onwards is currently not supported: The user encounters `ImportError: cannot import name 'MutableSequence' from 'collections'` if running on Python 3.10. This is because of a [known issue](https://github.com/CPJKU/madmom/issues/509) with `madmom`. Until that's fixed, I suggest changing the readme to say that `Python==3.9` is required.

**Comment by hugofloresgarcia** [comment]
updated the readme. thanks for that!

**Comment by tig3rmast3r** [comment]
it works here with python 3.11.4 on windows 10
you have to install madmom from source to get v0.17.dev0 where it has been fixed already
also numpy needs to be 1.23 at least on my machine
you may need to modify the file mask.py on line 197 too as described here https://github.com/hugofloresgarcia/vampnet/issues/12 i think is a Windows only issue

`(base) PS C:\Users\xxxxx\documents\vampnet\vampnet> python --version`
`Python 3.11.4`
`(base) PS C:\Users\xxxxx\documents\vampnet\vampnet> pip show numpy | findstr "Version"`
`Version: 1.23.0`
`(base) PS C:\Users\xxxxx\documents\vampnet\vampnet> pip show madmom | findstr "Version"`
`Version: 0.17.dev0`
