### ISSUE TITLE
lac package missing 

### ISSUE THREAD

**Issue by javanasse** [hugofloresgarcia/vampnet#2]
Just pulled most recent changes and the `lac` package is still missing. 

```console
ModuleNotFoundError: No module named 'lac'
```

Error is thrown line 14 in [`interface.py`](https://github.com/hugofloresgarcia/vampnet/blob/91e3ceb923bbd34a2cc78e1ccaf8088b4d9c7e87/vampnet/interface.py#L14)

**Comment by hugofloresgarcia** [comment]
Ah! We renamed one of our packages from `lac` to `dac` a bit ago and missed renaming it on this branch. Should be fixed as of 4d1e39c1c90cb092950f60f146ef30e483b6a623. 

Also, note that you'll have to pip install my fork of audiotools for now. I've updated the README to reflect that. Lmk if this works!

**Comment by hugofloresgarcia** [comment]
After running into errors,, I decided to revert use of the `dac` library back to the `lac` library. Installing vampnet should work now with just `pip install -e .`. See the most recent changes: bdcf1d8642781f084c35d01065a0fe03b7155126

**Comment by javanasse** [comment]
Looking better! 

Do you have this pytorch file? It was not in the models directory when I downloaded the `models.zip`.

```console
No such file or directory: 'models/vampnet/codec.pth'
```

**Comment by hugofloresgarcia** [comment]
Hmm, it should be in this zenodo record: https://zenodo.org/record/8136629

**Comment by javanasse** [comment]
Thanks for all the help, hugo!
