### ISSUE TITLE
fixed seed gives different results (once)

### ISSUE THREAD

**Issue by tig3rmast3r** [hugofloresgarcia/vampnet#24]
it looks there is a problem on how vars are passed to the mask generation, in fact when you fix the seed for generation, the first generation is different from all the subequent ones, so just to make an exmple, if i set the seed as 123456, without touching anything else:
- first gen -> wavA
- 2nd gen -> wavB
- 3rd gen -> wavB
- 4th gen -> wavB
etc...

looks like some vars are not passed correctly to the generation and it retains the last ones
on the second pass values are correct
i've identified the problem in the mask wav as it's different on the first pass
i'm trying to understand what is happening but is out of my knowledge :)

I've tried with an older checkout too (before harp) and problem was there already, hope this helps

**Comment by hugofloresgarcia** [comment]
Ah, thanks for letting me know! Is there any chance you could provide some steps to reproduce the problem and know what's going wrong? Thanks!

**Comment by tig3rmast3r** [comment]
it happens all the times:
-launch gradio default model
-set seed with fixed number
-generate
-ganerate again
-the 2nd and following generations will be the same, the fist generation will be different

problem is within the mask creation, it looks that first it creates the mask and then it assign the seed, so first generation is going to use the older seed value.

**Comment by hugofloresgarcia** [comment]
I see! Thanks so much!

**Comment by tig3rmast3r** [comment]
your commit was throwinhg errors
this one works, thank you

def _vamp(data, return_mask=False):
    _seed = data[seed]
    if _seed != 0:
        at.util.seed(_seed)
