### ISSUE TITLE
how to resume fine tuning ?

### ISSUE THREAD

**Issue by tig3rmast3r** [hugofloresgarcia/vampnet#26]
i have a very large dataset to fine-tune. i would like to split the training during night time over the days.
i saw there is a resume option in the code, do i simply have to add
resume: true
into coarse.yml and c2f.yml ?
does it resume from checkpoint saved into "latest" ?
folder naming will be maintained ? i mean "finetunename"4k, "finetunemane"8k etc...
thanks

**Comment by hugofloresgarcia** [comment]
hi! adding a `--resume` flag at the end of your training command should work. 

so 
```
python  scripts/exp/train.py --args.load conf/generated/finetuned.yml --resume
```
should work!
