### ISSUE TITLE
Descript-audiotools conflict

### ISSUE THREAD

**Issue by mateusztobiasz** [hugofloresgarcia/vampnet#40]
Hello!

I wanted to play with VampNet model so I followed section "Setting up" included in README.md. I also used conda with Python 3.9 to create an environment. I cloned the repo but running `pip install -e ./vampnet` failed. I received this error message: 

![image](https://github.com/user-attachments/assets/62347cf8-985f-44f4-9d8c-781f71e37067)

It seems that there is some conflict between `vampnet` and `lac` packages regarding `descript-audiotools` version. I've been trying to change the specified version in `setup.py` from `0.7.2` to `0.7.3` but I've got the similar error which is pretty confusing: 

![image](https://github.com/user-attachments/assets/d19fe9be-5b25-4607-9dbf-64fd7000d221)

Is this a known issue? Thank you in advance for your response.

**Comment by f0k** [comment]
Installation works when exactly copying the specification from [lac's setup.py](https://github.com/hugofloresgarcia/lac/blob/main/setup.py) into vampnet's setup.py so there is no conflict. Note that vampnet points to descriptinc's repo with a version specifier, while lac points to Hugo's repo without a version specifier.

**Comment by hugofloresgarcia** [comment]
Thanks @f0k! just pushed a fix that fixes the audiotools version conflict.

**Comment by mateusztobiasz** [comment]
+1, @f0k anwser resolves this issue :)
