### ISSUE TITLE
Error when tring to do inference

### ISSUE THREAD

**Issue by Liujingxiu23** [hugofloresgarcia/vampnet#7]
python app.py --args.load conf/interface.yml --Interface.device cuda

 CUDA_VISIBLE_DEVICES=7 python app.py --args.load conf/interface.yml --Interface.device cuda
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmplf47cw2f
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmplf47cw2f/_remote_module_non_scriptable.py
loading wavebeat from ./models/wavebeat.pth
/data/liujingxiu/software/anaconda3/envs/vampnet/lib/python3.9/site-packages/pytorch_lightning/utilities/migration/migration.py:201: PossibleUserWarning: You have multiple `ModelCheckpoint` callback states in this checkpoint, but we found state keys that would end up colliding with each other after an upgrade, which means we can't differentiate which of your checkpoint callbacks needs which states. At least one of your `ModelCheckpoint` callbacks will not be able to reload the state.
  rank_zero_warn(
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.1.8 to v2.0.6. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file models/wavebeat.pth`
interface device is cuda
Traceback (most recent call last):
  File "/data/liujingxiu/MusicGen/vampnet/app.py", line 521, in <module>
    sample_cutoff,
NameError: name 'sample_cutoff' is not defined

**Comment by hugofloresgarcia** [comment]
Hi! Hm, seem to have missed that. Should be fixed in the latest `ismir` branch. Feel free to close the issue  if that works!
